application: todolist-umair
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- static_dir: images
  url: /images
  
- url: /.*
  script: index.py
  

